name: My First Workflow

on:
  workflow_dispatch:

  issues:
    types: [opened, reopened]

jobs:
  job1:
    runs-on: ubuntu-latest  # Use the appropriate runner for your project

    steps:
    - name: Step 1
      run: echo "This is my first step"
    - name: Step 2
      run: echo "This is my second step"
  job2:
    runs-on: ubuntu-latest  # Use the appropriate runner for your project
    steps:
    - name: Coways
      uses: actions/cowsay@v1
      with: 
        Text: "Ready to Production ship it"

    